### ISSUE TITLE
Site-navigation

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#33]
sidebar ->
- ~~Your courses~~
- ~~Browse courses~~
- ~~Karma events~~

---- ---- (modals)
- share karmanotes 'earn 5 points for every signup' *_broken *_
- upload notes 'earn 5-10 points for every file' \* do we still want this? **

---- ---- (info)
- Profile/status
      + Username / alias
      + Avatar
      + Otherwise the same, but more compact

---- ---- (context info boxes)
- Occasional info boxes that inform you and can be dismissed
      + Get more karma by ...
      + KarmaNotes now has NNN Notes
      + Welcome Foo University, a new university at KN with courses like...

**Comment by sethwoodworth** [comment]
@AndrewMagliozzi Two questions:
- Do we want an upload link in the left sidebar that looks like the 'share' modal?
- Do we want a `Getting Started` link in the left sidebar also?

**Comment by AndrewMagliozzi** [comment]
Hi Seth:

Yes to the left sidebar upload link.  Ideally it is called out like the
"share" modal but even more prominently.

As for the "getting started" link, I do want one, but it is a bit premature
because we don't yet have a page for that.  Can you make a simple page with
all of a user's initial actions to complete:
- Upload a File
- Setup your Profile
- Select Courses
- Invite Friends
- View a File
- Earn Responsibility

**Comment by sethwoodworth** [comment]
I made a page for it yesterday http://beta.karmanotes.org/getting-started 
So far it includes the profile tasks we created for the profile page, I have 
- add school
- add grad year
- invite a friend
- choose username (which doesn't need to be here anymore)

On the getting-started page, the items are crossed out if they've been completed, and I add a checkbox to the right side of the table.
I will build out the rest of these.
